config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'
  get 'transaction/create/income', to:'transactions#income'
  post 'transaction/create/income', to:'transactions#income_submit'
  get 'transaction/create/bankTransfer', to:'transactions#bankTransfer'
  post 'transaction/create/bankTransfer', to:'transactions#bankTransfer_submit'
  get 'transaction/create/expense', to:'transactions#expense' 
  post 'transaction/create/expense', to:'transactions#expense_create',as:'expense'  
  get 'accounts',to: 'accounts#index'
  get 'accounts/create', to:'accounts#create', as:'createAccount'
  post 'accounts/create', to:'accounts#create'
  delete 'accounts',to:'accounts#delete' , as:'deleteAccount'
  get 'accounts/update/:id', to: 'accounts#update'
  put 'accounts/update/:id', to: 'accounts#updated', as:'updateAccount'
  get 'transaction',to:'transactions#index'
  get 'wallet',to:'home#wallet'
  root to: "home#dashboard"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_checkrai
  # Defines the root path route ("/") 
  # root "posts#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :AllTranactions,only: [:index]
  def index
    # puts @transaction
  end

  def income
    @transaction=current_user.transactions.new
    @accounts=current_user.accounts.all
  end

  def income_submit
    if params[:transaction_type]==="Wallet"
      begin
        ActiveRecord::Base.transaction do
          current_user.incomes.create(wallet_id:current_user.wallet.id,amount:params[:Amount],date:params[:Date],note:params[:Note])
          current_user.wallet.increment(:balance, params[:Amount].to_i)
          current_user.wallet.save
          redirect_to action: "index"
        end
      rescue=>e
        puts e.message
      end
    else
      begin
        ActiveRecord::Base.transaction do
          current_user.incomes.create(account_id:params[:account_id],amount:params[:Amount],date:params[:Date],note:params[:Note])
          account = current_user.accounts.find(params[:account_id].to_i)
          account.increment(:balance, params[:Amount].to_i)
          account.save
          redirect_to action: "index"
        end
      rescue=>e
        puts e.message
      end
    end
  end

  def bankTransfer
    @transaction=current_user.transactions.new
    @accounts=current_user.accounts.all
  end

  def bankTransfer_submit
      begin
        ActiveRecord::Base.transaction do
          account = current_user.accounts.find(params[:account_id].to_i)
          if account.balance.to_i>=params[:Amount].to_i
            account.decrement(:balance,params[:Amount].to_i)
            account.save
            current_user.bank_transfers.create(account_id:params[:account_id],amount:params[:Amount],date:params[:Date],note:params[:Note])
            if params[:transaction_type]==="Bank-Transfer"
              if params[:account_id]===params[:account_id_r]
                flash[:alert]="Cannot transfer money between one account"
                redirect_to action: "bankTransfer"
                raise ActiveRecord::Rollback , "Cannot transfer money between one account"
              end
              current_user.incomes.create(account_id:params[:account_id_r],amount:params[:Amount],date:params[:Date],note:"Amount Recived From #{account.bank_name} #{account.account_number}")
              recevier_account = current_user.accounts.find(params[:account_id_r].to_i)
              recevier_account.increment(:balance, params[:Amount].to_i)
              recevier_account.save
            end
            redirect_to action: "index"   
          else
            flash[:alert]="Current balnce is low to withdraw the Amount"
            redirect_to action: "bankTransfer"
            raise ActiveRecord::Rollback , "Current balnce is low to withdraw the Amount"
            
          end
        end
      rescue=>e
        puts e.message
      end
  end

  def expense
    @expense=current_user.expenses.new  
    @accounts=current_user.accounts.all
  end



  def expense_create
    begin
      p=params[:expense]
      ActiveRecord::Base.transaction do
        if p[:paid_with]==='Account'
          account = current_user.accounts.find(p[:account_id].to_i)
          if account.balance.to_i>=p[:Amount].to_i
            account.decrement(:balance,p[:Amount].to_i)
            account.save
            current_user.expenses.create(account_id:p[:account_id],amount:p[:Amount],date:p[:Date],note:p[:Note],expense_type:p[:expense_type])
            redirect_to action: "index"
          else
            flash[:alert]="Account balnce is low to pay the expense Amount"
            redirect_to action: "expense"
          end
        elsif p[:paid_with]==="Wallet"
          if current_user.wallet.balance>=p[:Amount].to_i 
            wallet=current_user.wallet.decrement(:balance,p[:Amount].to_i)
            wallet.save
            current_user.expenses.create(wallet_id:wallet.id,amount:p[:Amount],date:p[:Date],note:p[:Note],expense_type:p[:expense_type])
            redirect_to action: "index"
          else
            flash[:alert]="Wallet balnce is low to pay the expense Amount"
            redirect_to action: "expense"  
          end
        end
      end
    rescue=>e
      flash[:alert]=e.message
    end
  end




  private
  def AllTranactions
    @transaction=current_user.transactions.order(created_at: :desc)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/bankTransfer.html.erb
<div class="row g-0">
  <div class="col-lg-4 col-md-3 col-0"></div>
  <div
    class="col-lg-4 col-md-6 border border-2 border-success rounded mt-5 p-3"
  >
    <h4>Add Transaction Details</h4>

    <%= form_with do |form| %>

    <div>
      <%= form.label :account_id, "Select an Account" %> <%=
      form.select:account_id, options_for_select(@accounts.map {
      |account|["#{account.bank_name} - #{account.account_number}", account.id]
      }), {},class: 'form-select' %>
    </div>

    <div>
      <%= form.label :transaction_type, "Transaction Type" %> <%=
      form.select:transaction_type, options_for_select(['Withdraw',
      'Bank-Transfer']),{},{class:'form-select',id:"transaction-type",
      data:{controller:'hello',action:"change->hello#change_transaction_type" }}
      %>
    </div>

    <div id="accounts" style="display: none">
      <%= form.label :account_id_r, "Select an Account" %> <%=
      form.select:account_id_r, options_for_select(@accounts.map {
      |account|["#{account.bank_name} - #{account.account_number}", account.id]
      }), {},class: 'form-select' %>
    </div>

    <div>
      <%= form.label :Date, "Select the date" %> <%= form.date_field :Date,
      max:0.days.ago, class:'form-control', required:true %>
    </div>
    <div>
      <%= form.label :Amount %> <%= form.text_field :Amount,
      class:'form-control',required:true ,placeholder: 'Enter Ammount' %>
    </div>

    <div>
      <%= form.label :Note %> <%= form.text_field :Note,
      class:'form-control',placeholder: 'Note(Optional)' %>
    </div>

    <center>
      <%= form.submit "Create Income Transaction",class:'btn btn-success mt-2'
      %>
    </center>
    <% end %>
  </div>
  <div class="col-lg-4 col-md-3"></div>
</div>

app/views/transactions/expense.html.erb
<div class="row g-0">
  <div class="col-lg-4 col-md-3 col-0"></div>
  <div
    class="col-lg-4 col-md-6 border border-2 border-success rounded mt-5 p-3"
  >
    <h4>Add Expense Details</h4>

    <%= form_with(model:@expense,url:expense_path) do |form| %>

    <div>
      <%= form.label :transaction_type, "Paid with" %> <%=
      form.select:paid_with, options_for_select(['Account',
      'Wallet']),{},{class:'form-select',id:"transaction-type",
      data:{controller:'hello',action:"change->hello#change_transaction_type" }}
      %>
    </div>

    <div id="accounts">
      <%= form.label :account_id, "Select an Account" %> <%=
      form.select:account_id, options_for_select(@accounts.map {
      |account|["#{account.bank_name} - #{account.account_number}", account.id]
      }), {},class: 'form-select' %>
    </div>
    <div>
      <%= form.label :expense_type, "Expense Type" %> 
      <%= form.select:expense_type, Expense.expense_types.keys,{}, class:'form-select'%>
    </div>
    <div>
      <%= form.label :Date, "Select the date" %> <%= form.date_field :Date,
      max:0.days.ago, class:'form-control', required:true %>
    </div>
    <div>
      <%= form.label :Amount %> <%= form.text_field :Amount,
      class:'form-control',required:true ,placeholder: 'Enter Ammount' %>
    </div>

    <div>
      <%= form.label :Note %> <%= form.text_field :Note,
      class:'form-control',placeholder: 'Note(Optional)' %>
    </div>

    <center>
      <%= form.submit "Create Expense Transaction",class:'btn btn-success mt-2'
      %>
    </center>
    <% end %>
  </div>
  <div class="col-lg-4 col-md-3"></div>
</div>

app/views/transactions/income.html.erb
<div class="row g-0">
  <div class="col-lg-4 col-md-3 col-0"></div>
  <div
    class="col-lg-4 col-md-6 border border-2 border-success rounded mt-5 p-3"
  >
    <h4>Add Transaction Details</h4>

    <%= form_with do |form| %>

    <div>
      <%= form.label :transaction_type, "Where did you recieve" %> <%=
      form.select:transaction_type, options_for_select(['Account',
      'Wallet']),{},{class:'form-select',id:"transaction-type",
      data:{controller:'hello',action:"change->hello#change_transaction_type" }}
      %>
    </div>

    <div id="accounts">
      <%= form.label :account_id, "Select an Account" %>
      <%= form.select:account_id, options_for_select(@accounts.map { |account|["#{account.bank_name} - #{account.account_number}", account.id] }), {},class: 'form-select' %>
    </div>
    <div>
      <%= form.label :Date, "Select the date" %> <%= form.date_field :Date,
      max:0.days.ago, class:'form-control', required:true %>
    </div>
    <div>
      <%= form.label :Amount %> <%= form.text_field :Amount,
      class:'form-control',required:true ,placeholder: 'Enter Ammount' %>
    </div>

    <div>
      <%= form.label :Note %> <%= form.text_field :Note,
      class:'form-control',placeholder: 'Note(Optional)' %>
    </div>

    <center>
      <%= form.submit "Create Income Transaction",class:'btn btn-success mt-2'
      %>
    </center>
    <% end %>
  </div>
  <div class="col-lg-4 col-md-3"></div>
</div>

app/views/transactions/index.html.erb
<div class="d-flex justify-content-between align-items-center py-2">
  <div class="">
    <h1>Want to Add A Transaction</h1>
  </div>
  <div class="">
    <%= link_to 'Income' ,transaction_create_income_path, class:"r-link"%> <%=
    link_to 'Bank Transfer' ,transaction_create_bankTransfer_path,
    class:"r-link"%> <%= link_to 'Expense' , transaction_create_expense_path ,
    class:"r-link"%>
  </div>
</div>

<ul class="nav nav-pills nav-justified align-items-center">
  <li
    class="nav-item btn btn-primary"
    data-controller="hello"
    data-action="click->hello#Tabs"
    data-hello-value="Income"
  >
    Income
  </li>
  <li
    class="nav-item btn-primary"
    data-controller="hello"
    data-action="click->hello#Tabs"
    data-hello-value="Bank-Transfer"
  >
    Bank Transfer
  </li>
  <li
    class="nav-item btn-primary"
    data-controller="hello"
    data-action="click->hello#Tabs"
    data-hello-value="Expense"
  >
    Expense
  </li>
</ul>

<div id="Income"><%= render(IncomeComponent.new(user:current_user)) %></div>
<div id="Bank-Transfer" style="display: none">
  <%= render(BanktransferComponent.new(user:current_user)) %>
</div>
<div id="Expense" style="display: none">
  <%= render(ExpenseComponent.new(user:current_user)) %>
</div>