config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'
  get 'transaction/create/income', to:'transactions#income'
  post 'transaction/create/income', to:'transactions#income_submit'
  get 'transaction/create/bankTransfer', to:'transactions#bankTransfer'
  post 'transaction/create/bankTransfer', to:'transactions#bankTransfer_submit'
  get 'transaction/create/expense', to:'transactions#expense' 
  post 'transaction/create/expense', to:'transactions#expense_create',as:'expense'  
  get 'accounts',to: 'accounts#index'
  get 'accounts/create', to:'accounts#create', as:'createAccount'
  post 'accounts/create', to:'accounts#create'
  delete 'accounts',to:'accounts#delete' , as:'deleteAccount'
  get 'accounts/update/:id', to: 'accounts#update'
  put 'accounts/update/:id', to: 'accounts#updated', as:'updateAccount'
  get 'transaction',to:'transactions#index'
  get 'wallet',to:'home#wallet'
  root to: "home#dashboard"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_checkrai
  # Defines the root path route ("/") 
  # root "posts#index"
end

app/views/layouts/_footer.html.erb
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
  crossorigin="anonymous"
/>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
  crossorigin="anonymous"
></script>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
/>
<%= javascript_include_tag "https://cdn.jsdelivr.net/npm/chart.js@3.7.0/dist/chart.min.js" %> 
<%= javascript_include_tag "https://cdn.jsdelivr.net/npm/chartkick@4.1.1/dist/chartkick.min.js" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand">Expense Manager</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="collapse navbar-collapse justify-content-end"
      id="navbarNavAltMarkup"
    >
      <div class="navbar-nav">
        <a class="nav-link <%if request.path=='/'%> active<%end%>" href="/"
          >Dashboard</a
        >
        <%= link_to 'Accounts', accounts_path, class: 'nav-link' + (request.path == '/accounts' ? ' active' : '') %>
        <%= link_to 'Transactions', transactions_index_path, class: 'nav-link' + (request.path == '/transaction' ? ' active' : '') %>
        <%= link_to 'Wallet', wallet_path, class: 'nav-link' + (request.path == '/wallet' ? ' active' : '') %>
        <a class="nav-link">
          <%= button_to 'Sign Out',destroy_user_session_path,method:
          :delete,class:"sign-out"%>
        </a>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body> 
    <%if notice%>
    <script>
      alert('<%= notice%>');
    </script>
    <%end%>
    <% if flash[:alert].is_a?(Hash) %>
        <% flash[:alert].each do |key, value| %>
          <strong><%= key.humanize %>:</strong>
          <% if value.is_a?(Array) %>
            <ul>
              <% value.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          <% else %>
            <%= value %>
          <% end %>
        <% end %>
    <% elsif flash[:alert] %>
        <p><%= flash[:alert] %></p>
    <% end %>
    <% if current_user%>
    <%= render partial: 'layouts/navbar'%>
    <%end%>
    <div class="container">
      <%= yield %>
    </div>
      <%= render partial: 'layouts/footer' %>
  </body>
</html>